// Generated by scripts/extract-title-glyphs.py — do not edit by hand.
// Letters cut from public/brand/etu-title-typography.webp; digits are
// assembled from letters until a digits sheet exists.

export interface SpriteGlyph {
  /** Cell in the atlas, px. */
  x: number
  y: number
  w: number
  /** Width of the letter body; the cell adds `margin` of glow each side. */
  advance: number
}

export const ETU_SPRITE_FONT = {
  art: '/brand/etu-glyphs.webp',
  energy: '/brand/etu-glyphs-energy.webp',
  width: 2050,
  height: 822,
  /** Every cell is this tall: margin + letter depth (face + extrusion) + margin. */
  frameHeight: 204,
  margin: 16,
  /** Face top to the bottom of the extrusion, px. */
  depth: 172,
  glyphs: {
    "A": {
      "x": 0,
      "y": 0,
      "w": 224,
      "advance": 192
    },
    "B": {
      "x": 226,
      "y": 0,
      "w": 188,
      "advance": 156
    },
    "C": {
      "x": 416,
      "y": 0,
      "w": 186,
      "advance": 154
    },
    "D": {
      "x": 604,
      "y": 0,
      "w": 184,
      "advance": 152
    },
    "E": {
      "x": 790,
      "y": 0,
      "w": 179,
      "advance": 147
    },
    "F": {
      "x": 971,
      "y": 0,
      "w": 188,
      "advance": 156
    },
    "G": {
      "x": 1161,
      "y": 0,
      "w": 195,
      "advance": 163
    },
    "H": {
      "x": 1358,
      "y": 0,
      "w": 222,
      "advance": 190
    },
    "I": {
      "x": 1582,
      "y": 0,
      "w": 114,
      "advance": 82
    },
    "J": {
      "x": 1698,
      "y": 0,
      "w": 170,
      "advance": 138
    },
    "K": {
      "x": 1870,
      "y": 0,
      "w": 178,
      "advance": 146
    },
    "L": {
      "x": 0,
      "y": 206,
      "w": 160,
      "advance": 128
    },
    "M": {
      "x": 162,
      "y": 206,
      "w": 197,
      "advance": 165
    },
    "N": {
      "x": 361,
      "y": 206,
      "w": 182,
      "advance": 150
    },
    "O": {
      "x": 545,
      "y": 206,
      "w": 189,
      "advance": 157
    },
    "P": {
      "x": 736,
      "y": 206,
      "w": 191,
      "advance": 159
    },
    "Q": {
      "x": 929,
      "y": 206,
      "w": 212,
      "advance": 180
    },
    "R": {
      "x": 1143,
      "y": 206,
      "w": 202,
      "advance": 170
    },
    "S": {
      "x": 1347,
      "y": 206,
      "w": 183,
      "advance": 151
    },
    "T": {
      "x": 1532,
      "y": 206,
      "w": 187,
      "advance": 155
    },
    "U": {
      "x": 1721,
      "y": 206,
      "w": 177,
      "advance": 145
    },
    "V": {
      "x": 0,
      "y": 412,
      "w": 189,
      "advance": 157
    },
    "W": {
      "x": 191,
      "y": 412,
      "w": 248,
      "advance": 216
    },
    "X": {
      "x": 441,
      "y": 412,
      "w": 222,
      "advance": 190
    },
    "Y": {
      "x": 665,
      "y": 412,
      "w": 211,
      "advance": 179
    },
    "Z": {
      "x": 878,
      "y": 412,
      "w": 201,
      "advance": 169
    },
    "0": {
      "x": 545,
      "y": 206,
      "w": 189,
      "advance": 157
    },
    "1": {
      "x": 1582,
      "y": 0,
      "w": 114,
      "advance": 82
    },
    "2": {
      "x": 1081,
      "y": 412,
      "w": 183,
      "advance": 151
    },
    "3": {
      "x": 1266,
      "y": 412,
      "w": 179,
      "advance": 147
    },
    "4": {
      "x": 1447,
      "y": 412,
      "w": 222,
      "advance": 190
    },
    "5": {
      "x": 1347,
      "y": 206,
      "w": 183,
      "advance": 151
    },
    "6": {
      "x": 1161,
      "y": 0,
      "w": 195,
      "advance": 163
    },
    "7": {
      "x": 1671,
      "y": 412,
      "w": 201,
      "advance": 169
    },
    "8": {
      "x": 226,
      "y": 0,
      "w": 188,
      "advance": 156
    },
    "9": {
      "x": 0,
      "y": 618,
      "w": 195,
      "advance": 163
    }
  } as Record<string, SpriteGlyph>,
} as const
